name: belotte
description: "Belote Contree Online - Jeu de cartes multijoueur"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  web_socket_channel: ^3.0.2
  go_router: ^14.8.1
  shared_preferences: ^2.3.5
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
